#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: Contracts CI / Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build contracts
        run: yarn workspace contracts run build
      - name: Test contracts
        run: yarn workspace contracts run test
      - name: Lint contracts
        run: yarn workspace contracts lint
        env:
          CI: true
