#
# ci.yml
#
# Run tests for all pushed commits and opened pull requests on Github.
#

name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Yarn install, build, & test
        run: |
          yarn install
          yarn workspace contracts run build
          yarn workspace contracts run test
        env:
          CI: true
